#!/usr/bin/env python3
"""Convert Elementary 1/2 or Pre-Intermediate, without review or verification.

Reuse the Starter geometry/font pipeline, but disable Starter-only coordinates
and post-conversion audits. Rendering and device review are deliberately manual.
"""
import argparse
from concurrent.futures import ProcessPoolExecutor, as_completed
import contextlib
import importlib.util
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / '.cache/irodori-elementary'
LEVELS = {
    1: ('a21', '初级1', '初級1', '02_初级1_Elementary1_A2', 'Y'),
    2: ('a22', '初级2', '初級2', '03_初级2_Elementary2_A2', 'Z'),
    3: ('a2b1', '初中级', '初中級', '04_初中級_PreIntermediate_A2-B1', 'ZZ'),
}


def convert(job):
    number, lesson, source, node, resume = job
    level, label, footer_label, _, _ = LEVELS[number]
    cache = CACHE / level
    record_path = cache / f'l{lesson:02}' / 'conversion.json'
    if resume and record_path.exists():
        return json.loads(record_path.read_text())
    cache.mkdir(parents=True, exist_ok=True)
    font_dir = cache / f'fonts-l{lesson:02}'
    log = cache / f'l{lesson:02}.log'
    with log.open('w') as stream, contextlib.redirect_stdout(stream), contextlib.redirect_stderr(stream):
        if not (font_dir / 'fonts.json').exists():
            subprocess.run([node, str(ROOT / 'scripts/lib/irodori/extract-fonts.cjs'),
                            str(source), str(font_dir)], check=True, stdout=stream, stderr=stream)
        spec = importlib.util.spec_from_file_location('irodori_builder', ROOT / 'scripts/build-irodori-starter.py')
        builder = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(builder)
        record = builder.build(source, lesson, cache, CACHE / 'epubs', level=level,
                               label=label, footer_label=footer_label, audit=False)
    record['level'] = label
    record['sourceFile'] = source.name
    record_path.write_text(json.dumps(record, ensure_ascii=False, indent=2))
    return record


def publish(records, preintermediate=False):
    """Copy completed conversions and write runtime metadata; no validation pass."""
    rows = []
    for record in records:
        filename = f'{record["id"]}.epub'
        shutil.copyfile(CACHE / 'epubs' / filename,
                        ROOT / 'entry/src/main/resources/rawfile/reader' / filename)
        rows.append({key: record[key] for key in
                     ['lessonId', 'id', 'level', 'titles', 'fileBytes', 'cache']})
    code = '''// Generated by scripts/build-irodori-elementary.py. Manual review pending.
export interface IrodoriElementaryEdition {
  lessonId: string;
  id: string;
  level: string;
  titles: string[];
  fileBytes: number;
  cache: string;
}
export const IRODORI_ELEMENTARY_EDITIONS: IrodoriElementaryEdition[] = '''
    code += json.dumps(rows, ensure_ascii=False, indent=2) + ';\n'
    name = 'IrodoriElementaryContent.ets'
    if preintermediate:
        code = code.replace('IrodoriElementaryEdition', 'IrodoriPreIntermediateEdition')
        code = code.replace('IRODORI_ELEMENTARY_EDITIONS', 'IRODORI_PREINTERMEDIATE_EDITIONS')
        name = 'IrodoriPreIntermediateContent.ets'
    (ROOT / 'entry/src/main/ets/services' / name).write_text(code)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path, help='IRODORI root containing course directories')
    parser.add_argument('--levels', choices=['1,2', '3', '1,2,3'], default='1,2',
                        help='1,2: Elementary; 3: Pre-Intermediate; default preserves the Elementary workflow')
    parser.add_argument('--node', default='node')
    parser.add_argument('--jobs', type=int, default=3)
    parser.add_argument('--resume', action='store_true', help='Reuse completed conversions after an interrupted run; inputs must be unchanged')
    args = parser.parse_args()
    selected = [int(value) for value in args.levels.split(',')]
    jobs = []
    for number in selected:
        _, _, _, directory, prefix = LEVELS[number]
        source_dir = args.source / directory / '教材'
        for lesson in range(1, 19):
            sources = [p for p in source_dir.glob('*.pdf')
                       if re.search(rf'(?:^|_){prefix}_L{lesson:02}(?:_|\.)', p.name)]
            if len(sources) != 1:
                raise ValueError(f'Expected one source PDF for {LEVELS[number][1]} lesson {lesson}: {sources}')
            jobs.append((number, lesson, sources[0], args.node, args.resume))
    records = []
    failures = []
    with ProcessPoolExecutor(max_workers=max(1, args.jobs)) as pool:
        pending = {pool.submit(convert, job): job for job in jobs}
        for future in as_completed(pending):
            number, lesson, *_ = pending[future]
            try:
                record = future.result()
                records.append(record)
                print(f'Converted {record["lessonId"]}: {record["pageCount"]} pages ({len(records)}/{len(jobs)})', flush=True)
            except Exception as error:
                failures.append(f'{LEVELS[number][1]} L{lesson:02}: {error}')
                print(f'Conversion failed: {failures[-1]}', flush=True)
    if failures:
        raise RuntimeError('\n'.join(failures))
    records.sort(key=lambda record: record['lessonId'])
    elementary = [r for r in records if r['level'] != '初中级']
    preintermediate = [r for r in records if r['level'] == '初中级']
    if elementary:publish(elementary)
    if preintermediate:publish(preintermediate, preintermediate=True)
    summary = {'lessons': len(records), 'pages': sum(r['pageCount'] for r in records),
               'bytes': sum(r['fileBytes'] for r in records), 'verification': 'not_run',
               'lessonsByLevel': {label: sum(r['level'] == label for r in records)
                                  for number in selected for label in [LEVELS[number][1]]}}
    summary_name = 'conversion.json' if selected == [1, 2] else f'conversion-levels-{args.levels.replace(",", "-")}.json'
    (CACHE / summary_name).write_text(json.dumps({'totals': summary, 'lessons': records},
                                                    ensure_ascii=False, indent=2))
    print(json.dumps(summary, ensure_ascii=False), flush=True)


if __name__ == '__main__':
    main()
