#!/usr/bin/env python3
"""Validate every packaged spine, local resource and live source-font glyph."""
import argparse,hashlib,io,json,re,sys,zipfile
from pathlib import Path,PurePosixPath
from xml.etree import ElementTree as ET
from fontTools.ttLib import TTFont
ROOT=Path(__file__).resolve().parents[1]

def verify(epub,record):
 raw=epub.read_bytes()
 assert hashlib.sha256(raw).hexdigest()==record['epubSha256'],f'{epub}: digest'
 assert len(raw)==record['fileBytes'],f'{epub}: bytes'
 with zipfile.ZipFile(epub) as z:
  assert z.namelist()[0]=='mimetype' and z.read('mimetype')==b'application/epub+zip'
  names=set(z.namelist());opf=ET.fromstring(z.read('OEBPS/content.opf'))
  ns={'o':'http://www.idpf.org/2007/opf'};manifest={x.get('id'):x.get('href') for x in opf.findall('o:manifest/o:item',ns)}
  spine=opf.findall('o:spine/o:itemref',ns)
  assert [manifest[x.get('idref')] for x in spine]==[f'p{i}.xhtml' for i in range(1,record['pageCount']+1)]
  for path in manifest.values():assert 'OEBPS/'+path in names,(epub,path)
  css=z.read('OEBPS/style.css').decode();faces={}
  for family,path in re.findall(r'font-family:([^;]+);src:url\(([^)]+)\)',css):
   assert 'OEBPS/'+path in names
   font=TTFont(io.BytesIO(z.read('OEBPS/'+path)));faces[family]=font.getBestCmap()
  count=0
  for i in range(1,record['pageCount']+1):
   before=count
   root=ET.fromstring(z.read(f'OEBPS/p{i}.xhtml'))
   for el in root.iter():
    for attr in ['href','src']:
     value=el.get(attr)
     if value and not value.startswith('#'):assert 'OEBPS/'+value.split('#')[0] in names,(epub,i,value)
    style=el.get('style','');match=re.search(r'font-family:([^;!]+)',style)
    if match:
     family=match[1]
     for char in el.text or '':
      if char.isspace():continue
      assert family in faces and ord(char) in faces[family],(epub,i,family,char)
      count+=1
   audit=record['pages'][i-1]
   assert count-before+audit['imageCharacters']==audit['bodyCharacters'],(epub,i,'character partition')
  return count

def main():
 ap=argparse.ArgumentParser();ap.add_argument('--cache',type=Path,default=ROOT/'.cache/irodori-starter');ap.add_argument('--publish',action='store_true');a=ap.parse_args()
 records=[];live=0
 for lesson in [0]+list(range(2,19)):
  record=json.loads((a.cache/f'l{lesson:02}/audit.json').read_text());epub=a.cache/'epubs'/f'{record["id"]}.epub'
  live+=verify(epub,record);records.append(record)
  assert all(p['unmapped']==0 for p in record['pages'])
  print(f'Validated L{lesson:02}: {record["pageCount"]} pages, {record["fileBytes"]} bytes')
 summary={'lessons':len(records),'pages':sum(r['pageCount'] for r in records),'bodyCharacters':sum(p['bodyCharacters'] for r in records for p in r['pages']),
  'imageCharacters':sum(p['imageCharacters'] for r in records for p in r['pages']),'liveFontCharacters':live,'nativeTables':sum(p['nativeTables'] for r in records for p in r['pages']),
  'bytes':sum(r['fileBytes'] for r in records)}
 (a.cache/'validation.json').write_text(json.dumps(summary,indent=2));print(summary)
 if a.publish:
  rows=[]
  for r in records:
   (ROOT/'entry/src/main/resources/rawfile/reader'/f'{r["id"]}.epub').write_bytes((a.cache/'epubs'/f'{r["id"]}.epub').read_bytes())
   rows.append({k:r[k] for k in ['lessonId','id','titles','fileBytes','cache']})
  code='''// Generated by scripts/verify-irodori-starter.py --publish after validation.
export interface IrodoriStarterEdition {
  lessonId: string;
  id: string;
  titles: string[];
  fileBytes: number;
  cache: string;
}
export const IRODORI_STARTER_EDITIONS: IrodoriStarterEdition[] = '''+json.dumps(rows,ensure_ascii=False,indent=2)+';\n'
  (ROOT/'entry/src/main/ets/services/IrodoriStarterContent.ets').write_text(code)
  (ROOT/'docs/IRODORI_STARTER_AUDIT.json').write_text(json.dumps({'totals':summary,'lessons':[{k:v for k,v in r.items() if k!='fonts'} for r in records]},ensure_ascii=False,indent=2)+'\n')
if __name__=='__main__':main()
